[build]
  command = "hugo"
  publish = "public"
  # Specify the Hugo version. Make sure it matches the version you have locally.
  environment = { HUGO_VERSION = "0.120.3" }

# Additional configurations can go here if needed
